apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: scoring-mp
spec:
  initContainers:
  - name: init-bootstrap-properties
    image: docker.io/busybox:1.32
    imagePullPolicy: "Always"
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
    command:
      - /bin/sh
      - -c
      - |
        echo "mp.messaging.connector.liberty-kafka.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username=\"${KAFKA_USER}\" password=\"${KAFKA_PASSWORD}\";" >> tmpfile
        # If truststore & certificate information is needed (for instance, to connect to Event Streams on OCP), it would be added here...
        cp tmpfile /config/bootstrap.properties
    env:
      - name: KAFKA_USER
        valueFrom:
          secretKeyRef:
            name: "eventstreams-cred"
            key: username
      - name: KAFKA_PASSWORD
        valueFrom:
          secretKeyRef:
            name: "eventstreams-cred"
            key: password
    securityContext:
      runAsUser: 0
    volumeMounts:
      # /config is a default symlink to /opt/ol/wlp/usr/servers/defaultServer
      - name: openliberty-bootstrap
        mountPath: /config/
