apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    commit.image.appsody.dev/author: David Jones <djones6dev@gmail.com>
    commit.image.appsody.dev/committer: GitHub <noreply@github.com>
    commit.image.appsody.dev/contextDir: /simulator
    commit.image.appsody.dev/date: Fri Jan 29 12:49:03 2021 -0600
    commit.image.appsody.dev/message: Updated initialDelaySeconds for probes due to
      liberty startup (#77)
    image.opencontainers.org/created: "2021-01-29T18:51:38Z"
    image.opencontainers.org/documentation: https://github.com/ibm-cloud-architecture/refarch-reefer-ml
    image.opencontainers.org/revision: 0b194921646c950acf0dbb0b851bce39c0de065a-modified
    image.opencontainers.org/source: https://github.com/ibm-cloud-architecture/refarch-reefer-ml/tree/master
    image.opencontainers.org/url: https://github.com/ibm-cloud-architecture/refarch-reefer-ml
    stack.appsody.dev/configured: docker.io/appsody/python-flask:0.1
    stack.appsody.dev/created: 2019-11-14T10:29:19+0000
    stack.appsody.dev/digest: sha256:1405bd0d18b449f90d98ca31ba7c0a53d40dae6e62362a815cedde63bd2a18d2
    stack.appsody.dev/revision: b3e8a19b0a4b66a69daa8d1106f37bbe4167693a
    stack.appsody.dev/tag: appsody/python-flask:0.1.6
  creationTimestamp: null
  labels:
    app.appsody.dev/name: refarch-kc
    app.kubernetes.io/part-of: refarch-kc
    image.opencontainers.org/title: reefer-simulator
    stack.appsody.dev/version: 0.1.6
  name: reefer-simulator
spec:
  applicationImage: ibmcase/kcontainer-reefer-simulator-appsody:0.1.63
  createKnativeService: false
  env:
  - name: KAFKA_BROKERS
    valueFrom:
      configMapKeyRef:
        key: brokers
        name: kafka-brokers
  - name: MP_MESSAGING_INCOMING_REEFER_TELEMETRY_TOPIC
    valueFrom:
      configMapKeyRef:
        key: reeferTelemetryTopic
        name: kafka-topics
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  monitoring:
    labels:
      k8s-app: reefer-simulator
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 8080
    type: NodePort
  stack: python-flask
  version: 1.0.0
status: {}
