apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-ms
spec:
  template:
    spec:
      containers:
      - name: fleetms
        env:
          - name: KAFKA_APIKEY
            valueFrom:
              secretKeyRef:
                name: "eventstreams-apikey"
                key: binding
