apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: order-command-ms
spec:
  volumeMounts:
  - mountPath: /config/resources/security/es-ssl
    name: es-truststore-volume
