apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordercommandms-deployment
spec:
  template:
    spec:
      volumes:
      - name: es-truststore-volume
        secret:
          secretName: es-truststore-jks