apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: scoring-mp
spec:
  volumes:
  - name: openliberty-bootstrap
    emptyDir: {}
  - name: es-truststore-volume
    secret:
      secretName: eventstreams-truststore
