bases:
  - ../base

# Postgres CA mounted as /.postgresql/root.crt (for default SSLFactory)
patchesStrategicMerge:
  - ./service-account-patch.yaml
  - ./postgres-ca-volume-mount.yaml
  - ./postgres-ca-volume.yaml

patchesJson6902:
  - target:
      group: appsody.dev
      version: v1beta1
      kind: AppsodyApplication
      name: spring-container-ms
    path: ./appsody-env-patch.yaml
