apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  name: spring-container-ms
spec:
  volumes:
  - name: es-truststore-volume
    secret:
      secretName: es-truststore-jks
  - name: postgresql-ca-volume
    secret:
      secretName: postgresql-ca-pem