apiVersion: apps/v1
kind: Deployment
metadata:
  name: springcontainerms-deployment
spec:
  template:
    spec:
      containers:
      - name: springcontainerms
        volumeMounts:
          - mountPath: /config/resources/security/es-ssl
            name: es-truststore-volume