apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-ms
spec:
  template:
    spec:
      containers:
      - name: fleetms
        volumeMounts:
          - mountPath: /config/resources/security/es-ssl
            name: es-truststore-volume
