apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderqueryms-deployment
spec:
  template:
    spec:
      containers:
      - name: orderqueryms
        env:
          - name: TRUSTSTORE_ENABLED
            value: "true"
          - name: TRUSTSTORE_PWD
            valueFrom:
              secretKeyRef:
                name: es-truststore-jks
                key: password
          - name: TRUSTSTORE_PATH
            value: /config/resources/security/es-ssl/es-cert.jks