---
# Source: springcontainerms/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "springcontainerms-deployment"
  labels:
    chart: 'springcontainerms-1.0.0'
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: "springcontainerms-selector"
  template:
    metadata:
      labels:
        app: "springcontainerms-selector"
        version: "current"
    spec:
      serviceAccountName: kcontainer-runtime
      containers:
      - name: "springcontainerms"
        image: "ibmcase/kcontainer-spring-container-ms:latest"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
        resources:
          requests:
            cpu: "200m"
            memory: "300Mi"
        env:
          - name: PORT
            value: "8080"
          - name: APPLICATION_NAME
            value: "springcontainerms"
          #- name: JKS_LOCATION
          #  value: "$JAVA_HOME/jre/lib/security/cacerts"
          - name: KAFKA_BROKERS
            valueFrom:
              configMapKeyRef:
                name: "kafka-brokers"
                key: brokers
          - name: BPM_ANOMALY
            valueFrom:
              configMapKeyRef:
                name: "bpm-anomaly"
                key: url
                optional: true
          - name: BPM_ANOMALY_LOGIN
            valueFrom:
              configMapKeyRef:
                name: "bpm-anomaly"
                key: login
                optional: true
          - name: BPM_ANOMALY_USER
            valueFrom:
              secretKeyRef:
                name: "bpm-anomaly"
                key: user
                optional: true
          - name: BPM_ANOMALY_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "bpm-anomaly"
                key: password
                optional: true
          - name: KCSOLUTION_CONTAINERS
            valueFrom:
              configMapKeyRef:
                name: "kafka-topics"
                key: containersTopic
          - name: KCSOLUTION_ORDERS
            valueFrom:
              configMapKeyRef:
                name: "kafka-topics"
                key: ordersTopic
          - name: KCSOLUTION_REJECTED_ORDERS
            valueFrom:
              configMapKeyRef:
                name: "kafka-topics"
                key: rejectedOrdersTopic
          - name: KCSOLUTION_ALLOCATED_ORDERS
            valueFrom:
              configMapKeyRef:
                name: "kafka-topics"
                key: allocatedOrdersTopic
          - name: LOGGING_CONTAINER_MS_ROOT
            value: "INFO"
          - name: LOGGING_CONTAINER_MS_CONSUMER_CONFIG
            value: "ERROR"
          - name: LOGGING_CONTAINER_MS_PRODUCER_CONFIG
            value: "ERROR"
          - name: KAFKA_APIKEY
            valueFrom:
              secretKeyRef:
                name: "eventstreams-apikey"
                key: binding
                optional: true
          - name: POSTGRESQL_CA_PEM
            valueFrom:
              secretKeyRef:
                name: "postgresql-ca-pem"
                key: binding
                optional: true
          - name: POSTGRESQL_URL
            valueFrom:
              secretKeyRef:
                name: "postgresql-url"
                key: binding
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: "postgresql-user"
                key: binding
          - name: POSTGRESQL_PWD
            valueFrom:
              secretKeyRef:
                name: "postgresql-pwd"
                key: binding
