apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: allocated-orders
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: bluewater-container
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: bluewater-problem
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: bluewater-ship
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: containers
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: container-anomaly-retry
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: container-anomaly-dead
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: errors
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: order-commands
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: orders
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: reefer-telemetry
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: rejected-orders
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
---
