apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: my-cluster
  name: eda-integration-kafka-user
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
    - host: '*'
      operation: IdempotentWrite
      resource:
        name: '*'
        patternType: literal
        type: cluster
      type: allow
    - host: '*'
      operation: Read
      resource:
        name: assets-arch-eda
        patternType: prefix
        type: topic
      type: allow
    - host: '*'
      operation: Describe
      resource:
        name: assets-arch-eda
        patternType: prefix
        type: topic
      type: allow
    - host: '*'
      operation: Read
      resource:
        name: '*'
        patternType: literal
        type: group
      type: allow
    - host: '*'
      operation: Write
      resource:
        name: assets-arch-eda
        patternType: prefix
        type: topic
      type: allow
    - host: '*'
      operation: Create
      resource:
        name: assets-arch-eda
        patternType: prefix
        type: topic
      type: allow
    - host: '*'
      operation: Describe
      resource:
        name: assets-arch-eda
        patternType: prefix
        type: topic
      type: allow
    - host: '*'
      operation: Describe
      resource:
        name: '*'
        patternType: literal
        type: transactionalId
      type: allow
    - host: '*'
      operation: Write
      resource:
        name: '*'
        patternType: literal
        type: transactionalId
      type: allow
    type: simple
