apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: kc-dev-kafka
  namespace: openshift-gitops
spec:
  destination:
    namespace: kc-dev
    server: https://kubernetes.default.svc
  project: kc-solution
  source:
    path: environments/kc-dev/apps/strimzi/overlays
    repoURL: https://github.com/ibm-cloud-architecture/refarch-kc-gitops.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
