# Configures endpoints and settings for the BPM service.
#
# These values are suitable for running the integration tests, which includes a test for the 'Dead Letter Queue' pattern.
# The expectation is that the login to BPM will succeed, but the attempt to interact with BPM will fail, triggering a
# message to the container-anomaly-retry topic. After a number of retries, a message will instead be sent to the 
# container-anomaly-dead topic.
apiVersion: v1
kind: ConfigMap
metadata:
  name: bpm-anomaly
data:
  url: "http://localhost:8080/bpm_mockup/bpm_process_404"  # BPM workflow endpoint
  login: "http://localhost:8080/bpm_mockup/login"          # BPM authentication endpoint
  expiration: "100"                                        # number of seconds the auth token expires after
  anomalyThreshold: "3"                                    # number of anomaly events to receive before calling BPM
