apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-topics
data:
  bluewaterContainerTopic: bluewaterContainer
  bluewaterProblemTopic: bluewaterProblem
  bluewaterShipTopic: bluewaterShip
  containersTopic: containers
  containerAnomalyRetryTopic: container-anomaly-retry
  containerAnomalyDeadTopic: container-anomaly-dead
  errorsTopic: errors
  orderCommandsTopic: order-commands
  ordersTopic: orders
  reeferTelemetryTopic: reefer-telemetry
