bases:
  - ../../apps/refarch-kc

resources:
  - ./namespace.yaml
  - ./service-account.yaml
  - ./kafka-topics-configmap.yaml
  - ./bpm-configmap.yaml

secretGenerator:
  - name: eventstreams-cred
    files:
      - ./credentials/eventstreams-cred/username
      - ./credentials/eventstreams-cred/password
  - name: eventstreams-truststore
    files:
      - ./credentials/eventstreams-truststore/es-cert.p12
  - name: eventstreams-truststore-pwd
    files:
      - ./credentials/eventstreams-truststore/password
  - name: eventstreams-cert-pem
    files:
      - ./credentials/eventstreams-pem/es-cert.pem
  - name: postgresql-url
    files:
      - ./credentials/postgresql-url/binding
  - name: postgresql-user
    files:
      - ./credentials/postgresql-user/binding
  - name: postgresql-pwd
    files:
      - ./credentials/postgresql-pwd/binding
  - name: postgresql-ca-pem
    files:
      - ./credentials/gsa-eda-sandbox-db/root.crt
  - name: bpm-anomaly
    literals:
      - user='your-username'
      - password='your-password'

configMapGenerator:
  - name: kafka-brokers
    literals:
      - brokers="es-1-ibm-es-proxy-route-bootstrap-eventstreams.apps.ocp43.vg.gse-ocp.net:443"

generatorOptions:
  disableNameSuffixHash: true