apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  name: spring-container-ms
spec:
  volumeMounts:
  - mountPath: /config/resources/security/kafka-ssl
    name: kafka-truststore-volume
