apiVersion: apps/v1
kind: Deployment
metadata:
  name: voyagesms-deployment
spec:
  template:
    spec:
      containers:
      - name: voyagesms
        env:
          - name: CERTS_ENABLED
            value: "true"
          - name: CERTS_PATH
            value: /etc/ssl/certs/kcontainer/es-cert.pem