apiVersion: integration.ibm.com/v1beta1
kind: PlatformNavigator
metadata:
  creationTimestamp: null
  generation: 1
  name: kc-dev-cp4i-pn
  namespace: kc-dev
spec:
  license:
    accept: true
    license: L-RJON-BZFQU2
  mqDashboard: true
  replicas: 1
  storage:
    class: ibmc-file-gold-gid
  version: 2021.2.1